unit TestUDunitCalculadora;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Vcl.Dialogs, Winapi.Windows, System.SysUtils, Vcl.ExtCtrls,
  UCalculadora, Vcl.Graphics, System.Variants, Winapi.Messages, Vcl.StdCtrls,
  Vcl.Controls, Vcl.Forms, System.Classes;

type
  // Test methods for class TFCalculadora

  TestTFCalculadora = class(TTestCase)
  strict private
    FFCalculadora: TFCalculadora;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestFormShow;
    procedure TestBtDividirClick;
    procedure TestSomar;
    procedure TestDividir;
  end;

implementation

procedure TestTFCalculadora.SetUp;
begin
  //FFCalculadora := TFCalculadora.Create;
end;

procedure TestTFCalculadora.TearDown;
begin
  FFCalculadora.Free;
  FFCalculadora := nil;
end;

procedure TestTFCalculadora.TestFormShow;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FFCalculadora.FormShow(Sender);
  // TODO: Validate method results
end;

procedure TestTFCalculadora.TestBtDividirClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FFCalculadora.BtDividirClick(Sender);
  // TODO: Validate method results
end;

procedure TestTFCalculadora.TestSomar;
var
  ReturnValue: Integer;
  CNum2: Integer;
  cNum1: Integer;
begin
  // TODO: Setup method call parameters
  ReturnValue := FFCalculadora.Somar(cNum1, CNum2);
  // TODO: Validate method results
end;

procedure TestTFCalculadora.TestDividir;
var
  ReturnValue: Integer;
  CNum2: Integer;
  cNum1: Integer;
begin
  // TODO: Setup method call parameters
  ReturnValue := FFCalculadora.Dividir(cNum1, CNum2);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTFCalculadora.Suite);
end.

